### ISSUE TITLE
Feat: 핀 초안 item 삭제 

### ISSUE THREAD

**Issue by taewok** [airbnb-clone-project/Frontend#14]
### 📃Description
> 핀 초안 item에서 삭제 modal 마크업과 삭제 기능

### 📌Todo
- [x] 삭제 modal 마크업
- [x] 핀 초안 item 삭제 기능
- [x] 핀 초안 선택시 bottom button 생성

### 📝ETC
> 기타사항
