### ISSUE TITLE
Style: pin 만들기 page

### ISSUE THREAD

**Issue by taewok** [airbnb-clone-project/Frontend#7]
### 📃Description
> pin 만들기 page 마크업

### 📌Todo
- [ ] 핀 초안 side bar
- [ ] 추가 옵션 div
- [ ] 파일, url 저장 div
- [ ] pin 정보 inputs
- [ ] 반응형 웹 적용

### 📝ETC
> 없음
